apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../anthos-bundles/cis-gke-v1.5.0/
  - ../../anthos-bundles/cis-k8s-v1.7.1/
  - ../../anthos-bundles/cost-reliability-v2023/
  - ../../anthos-bundles/mitre-v2024/
  - ../../anthos-bundles/nist-sp-800-53-r5/
  - ../../anthos-bundles/nist-sp-800-190/
  - ../../anthos-bundles/pci-dss-v3.2.1/
  - ../../anthos-bundles/pci-dss-v3.2.1-extended/
  - ../../anthos-bundles/pci-dss-v4.0/
  - ../../anthos-bundles/pss-restricted-v2022/
  - ../../bundles/asm-policy-v0.0.1/
  - ../../bundles/cis-k8s-v1.5.1/
  - ../../bundles/policy-essentials-v2022/
  - ../../bundles/psp-v2022/
  - ../../bundles/pss-baseline-v2022/

patches:
  - target:
      kind: K8sAllowedRepos
    path: allowed_repos.yaml
  - target:
      kind: K8sBlockAllIngress
    path: ingress_allow_list.yaml
  - target:
      name: '.*'
    path: enforcement_action.yaml