# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sProhibitRoleWildcardAccess
metadata:
  name: prohibit-role-wildcard-access
  annotations:
    # This constraint is not certified by CIS.
    description: "Restricts use of wildcards in Roles and ClusterRoles."
    bundles.validator.forsetisecurity.org/cis-k8s-v1.5.1: 5.1.3
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
    - gke-connect
    - resource-group-system
  parameters:
    exemptions:
      clusterRoles:
        - name: "config-management-operator"
        - name: "configsync.gke.io:ns-reconciler"
        - name: "cluster-admin"
        - name: "external-metrics-reader"
        - name: "gatekeeper-manager-role"
        - name: "istio-reader-clusterrole-asm-1124-1-istio-system"
        - name: "istio-reader-istio-system"
        - name: "istiod-clusterrole-asm-1124-1-istio-system"
        - name: "istiod-istio-system"
        - name: "kubelet-api-admin"
        - name: "metering"
        - name: "resource-group-manager-role"
        - name: "system:controller:disruption-controller"
        - name: "system:controller:generic-garbage-collector"
        - name: "system:controller:horizontal-pod-autoscaler"
        - name: "system:controller:namespace-controller"
        - name: "system:controller:resourcequota-controller"
        - name: "system:gcp-controller-manager"
        - name: "system:gke-common-webhooks"
        - name: "system:gke-hpa-actor"
        - name: "system:gke-master-resourcequota"
        - name: "system:glbc-status"
        - name: "system:kube-controller-manager"
        - name: "system:kubestore-collector"
        - name: "system:kubelet-api-admin"
        - name: "system:managed-certificate-controller"
