apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata: # kpt-merge: /psp-privileged-container
  name: psp-privileged-container
  annotations:
    # This constraint is not certified by CIS.
    description: "Restricts containers with `securityContext.privileged` set to `true`."
spec:
  enforcementAction: dryrun # kpt-set: ${enforcementAction}
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
