apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPodsRequireSecurityContext
metadata:
  name: pods-require-security-context
  annotations:
    # This constraint is not certified by CIS.
    description: "Requires that Pods must have a `securityContext` defined."
spec:
  enforcementAction: dryrun # {"$kpt-set":"enforcementAction"}
