- op: replace
  path: /spec/parameters/allowList
  value:
    - ^istiod-asm-[0-9]{4}-[0-9]$
    - ^metrics-server$
    - ^kubernetes$
    - ^gke-connect-monitoring$
    - ^kube-dns$
    - ^istiod$
    - ^canonical-service-controller-manager-metrics-service$
    - ^default-http-backend$
    - ^otel-collector$
    - ^gatekeeper-webhook-service$
    - ^antrea$
    - ^istio-ingress$
    # Example of adding an allowed Ingress object
    - ^activity-log-api-springboot$
    - ^activity-log-ingest-springboot$
    - ^bar-workflow-orchestrator-springboot$
    - ^core-account-resin$
    - ^core-actioncache-resin$
    - ^core-actionprocessing-resin$
    - ^core-batchjobs-resin$
    - ^core-batchlogging-resin$
    - ^core-conversionservices-resin$
    - ^core-ftpdata-resin$
    - ^core-reportengine-resin$
    - ^core-rest-resin$
    - ^core-postback-delivery-resin$
    - ^core-solr$
    - ^compliance-app-resin$
    - ^content-index-billing-springboot$
    - ^content-index-social-springboot$
    - ^content-index-web-springboot$
    - ^content-index-search-springboot$
    - ^content-index-web-qa-springboot$
    - ^crawler-web-scrape-consumer-nodejs$
    - ^crawler-social-scrape-consumer-nodejs$
    - ^crawler-web-scrape-forced-consumer-nodejs$
    - ^crawler-web-scrape-ondemand-consumer-nodejs$
    - ^crawler-web-scrape-ranked-consumer-nodejs$
    - ^crawler-web-scrape-tracked-consumer-nodejs$
    - ^crawler-web-link-scan-consumer-nodejs$
    - ^crawler-web-compliance-batch-consumer-nodejs$
    - ^crawler-web-compliance-priority-consumer-nodejs$
    - ^finance-app-resin$
    - ^finance-batchjobs-resin$
    - ^finance-credit-springboot$
    - ^finance-sku-springboot$
    - ^finance-tax-springboot$
    - ^gateway-internal-apps$
    - ^icee-api-springboot$
    - ^icee-account-resync-job-springboot$
    - ^icee-ingest-al-springboot$
    - ^icee-ingest-resync-springboot$
    - ^icee-scheduled-jobs-springboot$
    - ^icee-ingest-dm-springboot$
    - ^icee-broadcast-springboot$
    - ^icee-job-springboot$
    - ^icee-ingest-springboot$
    - ^icee-match-springboot$
    - ^io-connectors-springboot$
    - ^io-engine-springboot$
    - ^io-gateway-springboot$
    - ^io-monitoring-dashboard-springboot$
    - ^io-operator-springboot$
    - ^io-scheduler-springboot$
    - ^io-tracer-api-springboot$
    - ^marketplace-approval-springboot$
    - ^messaging-springboot$
    - ^micro-app-ui-server-springboot$
    - ^notifications-mongodb$
    - ^operator-app-resin$
    - ^operator-batchjobs-resin$
    - ^operator-solr$
    - ^outreach-api-springboot$
    - ^outreach-ingest-springboot$
    - ^outreach-sender-springboot$
    - ^outreach-ui-springboot$
    - ^scheduled-jobs-springboot$
    - ^partner-prospecting-ui-springboot$
    - ^payout-pilot-springboot$
    - ^pds-resin$
    - ^platform-datastores$
    - ^platform-mysql$
    - ^redis-standalone$
    - ^report-builder-datalab-springboot$
    - ^report-builder-headless-springboot$
    - ^report-builder-reporting-springboot$
    - ^report-builder-scheduler-springboot$
    - ^report-builder-tools-springboot$
    - ^salesforce-integ-springboot$
    - ^scoring-web-partner-springboot$
    - ^selenium-grid-springboot$
    - ^remoting-adapter-springboot$
    - ^storefront-api-springboot$
    - ^techwriters-springboot$
    - ^tracking-resin$
    - ^tracking-calltracking-resin$
    - ^tracking-import-springboot$
    - ^tracking-kafkagw-resin$
    - ^tracking-tracking-resin$
    - ^traefik-standalone$
    - ^traefik-neg-stage-ha-*$
    - ^traefik-internal-l4-lb$
    - ^traefik-internal-api$
    - ^traefik-internal-dashboard$
    - ^traefik-standalone-api$
    - ^traefik-standalone-dashboard$
    - ^api-platform-springboot$
    - ^finance-app-resin$
    - ^marketplace-approval-springboot$
    - ^tracking-import-springboot$
    - ^tracking-call-resin$
    - ^tracking-calltracking-resin$
    - ^tracking-kafkagw-*$
    - ^tracking-*$
    - ^marketplace-approval-service-springboot$
    - ^compliance-batch-springboot$
    - ^content-index-change-checker-springboot$
    - ^graine-brain-springboot$
    - ^actioncache-mongodb$
    - ^content-index-grafana$
    - ^grafana$
    - ^gateway-internal-apps$
    - ^publisher-pro-xp-springboot$
    - ^monitoring-batch-springboot$
    - ^ia-intelligence-api-springboot$
    - ^survey-ui-springboot$
    - ^content-test-site-springboot$
    - ^salesforce-integration-springboot$
    - ^trk-web-cfg-api-springboot$
    - ^selenium-grid-.*$
    - ^creator-portal-services-springboot$
    - ^tracking-qa-springboot$
    - ^finance-billing-ui-springboot$
    - ^techfee-springboot$
    - ^gen-ai-springboot$
    - ^payments-app-springboot$
