# Copyright 2023 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireAdmissionController
metadata:
  name: cis-k8s-v1.7.1-require-admission-controller
  labels:
    policycontroller.gke.io/bundleName: cis-k8s-v1.7.1
  annotations:
    policycontroller.gke.io/bundleVersion: 202312.0-preview
    policycontroller.gke.io/constraintData: |-
      "{
        bundleName: 'cis-k8s-v1.7.1',
        bundleDisplayName: 'CIS Kubernetes Benchmark v1.7.1',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-cis-k8s-benchmark',
        bundleVersion: '202312.0-preview',
        bundleDescription: 'Use the CIS Kubernetes Benchmark 1.7.1 policy bundle with Policy Controller to evaluate the compliance of your cluster resources against the CIS Kubernetes Benchmark, which is a set of recommendations for configuring Kubernetes to support a robust security posture.',
        controlNumbers: '[5.2.1]',
        severity: 'UNSPECIFIED',
        description: 'Requires either Pod Security Admission or an external policy control system.',
        remediation: 'Every cluster requires a policy control system, either Pod Security Admission active for each namespace, or an external policy control system. See "Admission Controllers Reference" for more information: https://kubernetes.io/docs/concepts/security/pod-security-admission',
        minimumTemplateLibraryVersion: '1.17.0',
        constraintHash: 'cea801d744f58d7a21028a4fbc565cc37dad4de025d85b007993e90d159c1958'
      }"
spec:
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Namespace
    excludedNamespaces:
      - config-management-monitoring
      - config-management-system
      - gatekeeper-system
      - gmp-public
      - gmp-system
      - kube-node-lease
      - kube-public
      - kube-system
      - istio-system
  parameters:
    permittedValidatingWebhooks:
      - gatekeeper-validating-webhook-configuration
  enforcementAction: dryrun
